# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.6
python: 3.6

# Install the codecov pip dependency
install:
  - cd backend && pip install -r requirements

# Run the unit test
script:
  - cd backend && pytest

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) -t e2c76867-bf6e-4b2f-a933-1fd50dafcb22
