name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pwd
        ls
        cd backend
        pip install -r requirements.txt
#        pip install django coverage pytest pytest-django pytest-cov pytest-pythonpath codecov
    - name: Run Tests
      run: |
        pwd
        ls
        cd backend
        pytest
        codecov
        bash <(curl -s https://codecov.io/bash) -t e2c76867-bf6e-4b2f-a933-1fd50dafcb22
